/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    posts: Post;
    tags: Tag;
    categories: Category;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Post {
  id: string;
  title: string;
  subtitle: string;
  category?: {
    value: string | Category;
    relationTo: 'categories';
  };
  tags?:
    | {
        value: string;
        relationTo: 'tags';
      }[]
    | {
        value: Tag;
        relationTo: 'tags';
      }[];
  description?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Category {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
export interface Tag {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
